#!/bin/bash
# This script builds the Rusty Calico WASM32 SDK release.

# make the script fail for any failed command
set -e

rm -rf release/*
rm -rf web/*
rm -rf nodejs/*
rm -rf docs/*
rm -rf examples/nodejs/typescript/lib

mkdir -p release/calico-wasm32-sdk/web
mkdir -p release/calico-wasm32-sdk/nodejs
mkdir -p release/calico-wasm32-sdk/docs

# pushd .
# cd ../rpc/wrpc/wasm
# wasm-pack build --target web --out-name calico-rpc --out-dir web/calico-rpc --features wasm32-sdk $@
# popd

wasm-pack build --weak-refs --target web --out-name calico --out-dir web/calico-keygen --features wasm32-keygen $@
wasm-pack build --weak-refs --dev --target web --out-name calico --out-dir web/calico-keygen-dev --features wasm32-keygen $@

wasm-pack build --weak-refs --target web --out-name calico --out-dir web/calico-rpc --features wasm32-rpc $@
wasm-pack build --weak-refs --dev --target web --out-name calico --out-dir web/calico-rpc-dev --features wasm32-rpc $@

wasm-pack build --weak-refs --target web --out-name calico --out-dir web/calico-core --features wasm32-core $@
wasm-pack build --weak-refs --dev --target web --out-name calico --out-dir web/calico-core-dev --features wasm32-core $@

wasm-pack build --weak-refs --target web --out-name calico --out-dir web/calico --features wasm32-sdk $@
wasm-pack build --weak-refs --dev --target web --out-name calico --out-dir web/calico-dev --features wasm32-sdk $@

wasm-pack build --weak-refs --target nodejs --out-name calico --out-dir nodejs/calico --features wasm32-sdk $@
wasm-pack build --weak-refs --dev --target nodejs --out-name calico --out-dir nodejs/calico-dev --features wasm32-sdk $@

# wasm-pack build --target web --dev --out-name calico --out-dir build/docs/calico --features wasm32-sdk $@
typedoc --name "Calico WASM32 SDK - Key Generation" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/calico-keygen ./build/docs/calico-keygen.ts
typedoc --name "Calico WASM32 SDK - RPC" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/calico-rpc ./build/docs/calico-rpc.ts
typedoc --name "Calico WASM32 SDK - Core" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/calico-core ./build/docs/calico-core.ts
typedoc --name "Calico WASM32 SDK" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out docs/calico ./build/docs/calico.ts

# cp -r ../rpc/wrpc/wasm/web/calico-rpc release/calico-wasm32-sdk/web/calico-rpc
cp -r web/calico-keygen release/calico-wasm32-sdk/web/calico-keygen
cp -r web/calico-keygen-dev release/calico-wasm32-sdk/web/calico-keygen-dev

cp -r web/calico-rpc release/calico-wasm32-sdk/web/calico-rpc
cp -r web/calico-rpc-dev release/calico-wasm32-sdk/web/calico-rpc-dev

cp -r web/calico-core release/calico-wasm32-sdk/web/calico-core
cp -r web/calico-core-dev release/calico-wasm32-sdk/web/calico-core-dev

cp -r web/calico release/calico-wasm32-sdk/web/calico
cp -r web/calico-dev release/calico-wasm32-sdk/web/calico-dev

cp -r nodejs/calico release/calico-wasm32-sdk/nodejs/calico
cp -r nodejs/calico-dev release/calico-wasm32-sdk/nodejs/calico-dev

cp -r docs/calico-keygen release/calico-wasm32-sdk/docs/calico-keygen
cp -r docs/calico-rpc release/calico-wasm32-sdk/docs/calico-rpc
cp -r docs/calico-core release/calico-wasm32-sdk/docs/calico-core
cp -r docs/calico release/calico-wasm32-sdk/docs/calico

mkdir -p release/calico-wasm32-sdk/examples/data
cp -r examples/data/.gitignore release/calico-wasm32-sdk/examples/data/.gitignore
cp -r examples/nodejs release/calico-wasm32-sdk/examples/
cp -r examples/web release/calico-wasm32-sdk/examples/
cp -r examples/init.js release/calico-wasm32-sdk/examples/
cp -r examples/jsconfig.json release/calico-wasm32-sdk/examples/
cp -r examples/package.json release/calico-wasm32-sdk/examples/

pushd .
cd release/calico-wasm32-sdk/examples
npm install
popd

# tsc release/calico-wasm32-sdk/examples/nodejs/typescript/

cp index.html release/calico-wasm32-sdk/index.html
cp README.md release/calico-wasm32-sdk/README.md
cp CHANGELOG.md release/calico-wasm32-sdk/CHANGELOG.md
cp LICENSE release/calico-wasm32-sdk/LICENSE

node build/package-sizes.js
cp package-sizes.js release/calico-wasm32-sdk/package-sizes.js

pushd .
cd release
zip -q -r calico-wasm32-sdk.zip calico-wasm32-sdk
popd
